# Compile Noise Source as user space application

CC ?= gcc
CFLAGS +=-Wextra -Wall -pedantic -fPIC -O0 
#Hardening
CFLAGS +=-fwrapv --param ssp-buffer-size=4
ifneq (Darwin,$(shell uname))
LDFLAGS +=-Wl,-z,relro,-z,now
endif

GCCVERSIONFORMAT := $(shell echo `$(CC) -dumpversion | sed 's/\./\n/g' | wc -l`)
ifeq "$(GCCVERSIONFORMAT)" "3"
  GCC_GTEQ_490 := $(shell expr `$(CC) -dumpversion | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$$/&00/'` \>= 40900)
else
  GCC_GTEQ_490 := $(shell expr `$(CC) -dumpfullversion | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$$/&00/'` \>= 40900)
endif

ifeq "$(GCC_GTEQ_490)" "1"
  CFLAGS += -fstack-protector-strong
else
  CFLAGS += -fstack-protector-all
endif

JENT_DIR := jitterentropy
JENT_SRCS := $(wildcard $(JENT_DIR)/src/*.c) $(wildcard $(JENT_DIR)/arch/*.c)

NAME := jitterentropy-rng

# Compile all objects into a local directory. Emitting them next to the
# library sources (through the jitterentropy symlink) would leave objects
# built with this tool's flags inside src/ and arch/, which the library's
# own Makefile then silently picks up via VPATH - e.g. linking a
# libjitterentropy without JENT_CONF_ENABLE_INTERNAL_TIMER support.
OBJDIR := obj-rng
C_SRCS := $(JENT_SRCS) jitterentropy-rng.c
OBJS := $(addprefix $(OBJDIR)/,$(notdir $(C_SRCS:.c=.o)))

vpath %.c $(JENT_DIR)/src $(JENT_DIR)/arch

INCLUDE_DIRS := $(JENT_DIR) $(JENT_DIR)/src
LIBRARY_DIRS :=
LIBRARIES := rt pthread

CFLAGS += $(foreach includedir,$(INCLUDE_DIRS),-I$(includedir))
LDFLAGS += $(foreach librarydir,$(LIBRARY_DIRS),-L$(librarydir))
LDFLAGS += $(foreach library,$(LIBRARIES),-l$(library))

.PHONY: all clean distclean

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(OBJS) -o $(NAME) $(LDFLAGS)

$(OBJDIR)/%.o: %.c | $(OBJDIR)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c -o $@ $<

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	@- $(RM) $(NAME)
	@- $(RM) -r $(OBJDIR)

distclean: clean
