# Compile Noise Source as user space application

CC ?= gcc
CFLAGS +=-Wextra -Wall -pedantic -fPIC -O2 -DCONFIG_CRYPTO_CPU_JITTERENTROPY_SECURE_MEMORY
#Hardening
CFLAGS +=-fwrapv --param ssp-buffer-size=4
LDFLAGS +=-Wl,-z,relro,-z,now

GCCVERSIONFORMAT := $(shell echo `gcc -dumpversion | sed 's/\./\n/g' | wc -l`)
ifeq "$(GCCVERSIONFORMAT)" "3"
  GCC_GTEQ_490 := $(shell expr `gcc -dumpversion | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$$/&00/'` \>= 40900)
else
  GCC_GTEQ_490 := $(shell expr `gcc -dumpfullversion | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$$/&00/'` \>= 40900)
endif

ifeq "$(GCC_GTEQ_490)" "1"
  CFLAGS += -fstack-protector-strong
else
  CFLAGS += -fstack-protector-all
endif

NAME := jitterentropy-lfsroutput
C_SRCS := jitterentropy-base.c jitterentropy-lfsroutput.c
C_OBJS := ${C_SRCS:.c=.o}
OBJS := $(C_OBJS)

INCLUDE_DIRS :=
LIBRARY_DIRS :=
LIBRARIES := rt pthread

CFLAGS += $(foreach includedir,$(INCLUDE_DIRS),-I$(includedir))
LDFLAGS += $(foreach librarydir,$(LIBRARY_DIRS),-L$(librarydir))
LDFLAGS += $(foreach library,$(LIBRARIES),-l$(library))

.PHONY: all clean distclean

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(OBJS) -o $(NAME) $(LDFLAGS)

clean:
	@- $(RM) $(NAME)
	@- $(RM) $(OBJS)

distclean: clean
