/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/*
 * Character device interface for Jitter RNG.
 *
 * This registers a misc character device (/dev/jitterentropy). For every
 * open() a dedicated Jitter RNG entropy collector is allocated; it is freed
 * again on the matching release(). read() delivers entropy bytes obtained
 * from that per-open instance.
 *
 * The whole interface can be disabled at compile time by not setting the
 * CONFIG_EXTERNAL_JITTERENTROPY_CHARDEV configuration option (see
 * Kbuild.config). In that case the stubs in jitterentropy_chardev.h are used.
 *
 * Copyright (C) 2026, Stephan Mueller <smueller@chronox.de>
 */

#include <linux/fs.h>
#include <linux/kernel.h>
#include <linux/miscdevice.h>
#include <linux/module.h>
#include <linux/mutex.h>
#include <linux/slab.h>
#include <linux/uaccess.h>

#include "jitterentropy.h"
#include "jitterentropy_chardev.h"

/*
 * The OSR and flags used to allocate the per-open Jitter RNG instances are
 * shared with the crypto API interface and are configurable via the module
 * parameters of the same name (see jitterentropy_kcapi.c).
 */
extern unsigned int osr;
extern int flags;

/* Largest chunk handed to jent_read_entropy_safe() in one iteration. */
#define JENT_CHARDEV_READ_BUF_SIZE 256

/* Per-open state: each open() gets its own Jitter RNG instance. */
struct jent_chardev_ctx {
	struct mutex lock;
	struct rand_data *entropy_collector;
};

static int jent_chardev_open(struct inode *inode, struct file *file)
{
	struct jent_chardev_ctx *ctx;

	ctx = kzalloc(sizeof(*ctx), GFP_KERNEL);
	if (!ctx)
		return -ENOMEM;

	mutex_init(&ctx->lock);

	ctx->entropy_collector = jent_entropy_collector_alloc(osr, flags);
	if (!ctx->entropy_collector) {
		mutex_destroy(&ctx->lock);
		kfree(ctx);
		return -ENOMEM;
	}

	file->private_data = ctx;

	return 0;
}

static int jent_chardev_release(struct inode *inode, struct file *file)
{
	struct jent_chardev_ctx *ctx = file->private_data;

	if (!ctx)
		return 0;

	if (ctx->entropy_collector)
		jent_entropy_collector_free(ctx->entropy_collector);
	mutex_destroy(&ctx->lock);
	kfree(ctx);
	file->private_data = NULL;

	return 0;
}

static ssize_t jent_chardev_read(struct file *file, char __user *buf,
				 size_t nbytes, loff_t *ppos)
{
	struct jent_chardev_ctx *ctx = file->private_data;
	u8 *tmp;
	ssize_t ret = 0;

	if (!ctx)
		return -EFAULT;

	if (!nbytes)
		return 0;

	tmp = kmalloc(JENT_CHARDEV_READ_BUF_SIZE, GFP_KERNEL);
	if (!tmp)
		return -ENOMEM;

	if (mutex_lock_interruptible(&ctx->lock)) {
		ret = -ERESTARTSYS;
		goto out;
	}

	while (nbytes) {
		size_t towork = min_t(size_t, nbytes,
				      JENT_CHARDEV_READ_BUF_SIZE);
		ssize_t rc;

		/*
		 * jent_read_entropy_safe() reallocates the collector on
		 * intermittent health-test failures, hence the indirection.
		 * It returns the number of generated bytes (== towork) or a
		 * negative error code on a permanent/generic failure.
		 */
		rc = jent_read_entropy_safe(&ctx->entropy_collector, tmp,
					    towork);
		if (rc < 0) {
			if (ret == 0)
				ret = -EFAULT;
			break;
		}

		if (copy_to_user(buf, tmp, rc)) {
			if (ret == 0)
				ret = -EFAULT;
			break;
		}

		nbytes -= rc;
		buf += rc;
		ret += rc;

		/* Be cooperative for large requests. */
		if (need_resched()) {
			if (signal_pending(current)) {
				if (ret == 0)
					ret = -ERESTARTSYS;
				break;
			}
			cond_resched();
		}
	}

	mutex_unlock(&ctx->lock);

out:
	kfree_sensitive(tmp);
	return ret;
}

static const struct file_operations jent_chardev_fops = {
	.owner		= THIS_MODULE,
	.open		= jent_chardev_open,
	.release	= jent_chardev_release,
	.read		= jent_chardev_read,
};

static struct miscdevice jent_chardev_misc = {
	.minor	= MISC_DYNAMIC_MINOR,
	.name	= "jitterentropy",
	.fops	= &jent_chardev_fops,
	.mode	= 0444,
};

int jent_chardev_init(void)
{
	int ret = misc_register(&jent_chardev_misc);

	if (ret)
		pr_err("jitterentropy: failed to register character device: %d\n",
		       ret);
	else
		pr_info("jitterentropy: character device /dev/%s registered\n",
			jent_chardev_misc.name);

	return ret;
}

void jent_chardev_exit(void)
{
	misc_deregister(&jent_chardev_misc);
}
