/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/*
 * Hardware RNG (hwrng) interface for Jitter RNG.
 *
 * This registers the Jitter RNG with the kernel hw_random framework, exposing
 * it as /dev/hwrng (when selected as the current hwrng) and optionally letting
 * the kernel hwrng entropy thread (rngd in-kernel) feed the random pool.
 *
 * A single Jitter RNG instance is allocated when the hwrng is registered (at
 * module load) and freed when it is unregistered (at module unload). read
 * requests are served from that instance and serialized via a mutex.
 *
 * The whole interface can be disabled at compile time by not setting the
 * CONFIG_EXTERNAL_JITTERENTROPY_HWRNG configuration option (see Kbuild.config).
 * In that case the stubs in jitterentropy_hwrng.h are used.
 *
 * Copyright (C) 2026, Stephan Mueller <smueller@chronox.de>
 */

#include <linux/hw_random.h>
#include <linux/init.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/module.h>
#include <linux/mutex.h>
#include <linux/proc_fs.h>
#include <linux/seq_file.h>
#include <linux/slab.h>
#include <linux/version.h>

#include "jitterentropy.h"
#include "jitterentropy_error.h"
#include "jitterentropy_hwrng.h"
#include "jitterentropy_proc.h"

/*
 * The OSR and flags used to allocate the Jitter RNG instance are shared with
 * the crypto API interface and are configurable via the module parameters of
 * the same name (see jitterentropy_mod.c).
 */
extern unsigned int osr;
extern unsigned int flags;

/*
 * Entropy quality declared to the hw_random framework, expressed as the number
 * of bits of estimated entropy per 1024 bits of output (maximum 1024).
 *
 * The meaning of the default of 0 depends on the kernel version:
 *
 * - Kernels < 6.2: the device is registered without contributing to the
 *   kernel random pool automatically; the Jitter RNG output is still
 *   available via /dev/hwrng.
 *
 * - Kernels >= 6.2: the hw_random core promotes a driver quality of 0 to the
 *   global default (module parameter rng_core.default_quality, 1024 unless
 *   overridden), so the in-kernel hwrng thread will feed the random pool with
 *   full entropy credit. A per-driver opt-out no longer exists; boot with
 *   rng_core.default_quality=0 or lower /sys/class/misc/hw_random/rng_quality
 *   at runtime to prevent the automatic crediting. jent_hwrng_init() reports
 *   the effective quality after registration.
 *
 * Set a non-zero value (e.g. 1024, as the Jitter RNG is designed to deliver
 * full-entropy, conditioned output) to declare the quality explicitly.
 */
static unsigned int hwrng_quality = 0;
module_param(hwrng_quality, uint, S_IRUSR | S_IRGRP | S_IROTH);
MODULE_PARM_DESC(hwrng_quality,
		 "Jitter RNG hwrng entropy quality (bits per 1024 bits, 0..1024; on kernels >= 6.2 the hw_random core promotes 0 to rng_core.default_quality)");

/* State backing the single hwrng instance. */
struct jent_hwrng_ctx {
	struct mutex lock;
	struct rand_data *entropy_collector;
};

static struct jent_hwrng_ctx jent_hwrng_ctx;

static int jent_hwrng_read(struct hwrng *rng, void *data, size_t max, bool wait)
{
	struct jent_hwrng_ctx *ctx = &jent_hwrng_ctx;
	ssize_t ret;

	if (!max)
		return 0;

	/*
	 * Jitter entropy collection is CPU-bound and slow, and the mutex may be
	 * held by another reader while it generates (bounded by the hwrng core
	 * buffer size per call). A non-blocking caller (wait == false) must not
	 * sleep on it; report "no data available" instead so the hwrng core can
	 * fall back or retry. A blocking caller sleeps interruptibly so a
	 * /dev/hwrng reader stays killable while waiting.
	 */
	if (!wait) {
		if (!mutex_trylock(&ctx->lock))
			return 0;
	} else if (mutex_lock_interruptible(&ctx->lock)) {
		return -ERESTARTSYS;
	}
	/*
	 * jent_read_entropy_safe() reallocates the collector on intermittent
	 * health-test failures, hence the indirection. It returns the number
	 * of generated bytes (== max) or a negative error code on a
	 * permanent/generic failure.
	 */
	ret = jent_read_entropy_safe(&ctx->entropy_collector, data, max);
	mutex_unlock(&ctx->lock);

	if (ret < 0)
		return jent_map_read_error(ret);

	return (int)ret;
}

static struct hwrng jent_hwrng = {
	.name	= "jitterentropy",
	.read	= jent_hwrng_read,
};

/*
 * Status of the global hwrng Jitter RNG instance, exported read-only as
 * /proc/jitterentropy/hwrng_status. Reading it emits the JSON status string
 * produced by jent_status() (version, health-test state, runtime environment
 * and configuration) for the single instance backing /dev/hwrng.
 */
#define JENT_HWRNG_PROC_NAME	"hwrng_status"
#define JENT_HWRNG_STATUS_BUF_SIZE 4096

static struct proc_dir_entry *jent_hwrng_proc;

static int jent_hwrng_proc_status_show(struct seq_file *m, void *v)
{
	struct jent_hwrng_ctx *ctx = &jent_hwrng_ctx;
	char *buf;
	int ret;

	buf = kvzalloc(JENT_HWRNG_STATUS_BUF_SIZE, GFP_KERNEL);
	if (!buf)
		return -ENOMEM;

	/*
	 * The status is derived from the collector state; hold the same lock as
	 * the read path, which may reallocate the collector on health-test
	 * recovery, so it cannot be freed underneath jent_status().
	 */
	if (mutex_lock_interruptible(&ctx->lock)) {
		kvfree(buf);
		return -ERESTARTSYS;
	}
	if (ctx->entropy_collector)
		ret = jent_status(ctx->entropy_collector, buf,
				  JENT_HWRNG_STATUS_BUF_SIZE);
	else
		ret = -1;
	mutex_unlock(&ctx->lock);

	if (ret) {
		kvfree(buf);
		return -EIO;
	}

	seq_puts(m, buf);
	kvfree(buf);
	return 0;
}

int __init jent_hwrng_init(void)
{
	int ret;

	mutex_init(&jent_hwrng_ctx.lock);

	jent_hwrng_ctx.entropy_collector =
		jent_entropy_collector_alloc(osr, flags);
	if (!jent_hwrng_ctx.entropy_collector) {
		mutex_destroy(&jent_hwrng_ctx.lock);
		return -ENOMEM;
	}

	if (hwrng_quality > 1024)
		pr_warn("jitterentropy: hwrng_quality %u out of range, clamping to 1024\n",
			hwrng_quality);
	jent_hwrng.quality = (unsigned short)min_t(unsigned int, hwrng_quality,
						   1024);

	ret = hwrng_register(&jent_hwrng);
	if (ret) {
		pr_err("jitterentropy: failed to register hwrng device: %d\n",
		       ret);
		jent_entropy_collector_free(jent_hwrng_ctx.entropy_collector);
		jent_hwrng_ctx.entropy_collector = NULL;
		mutex_destroy(&jent_hwrng_ctx.lock);
		return ret;
	}

	/*
	 * Report the effective quality: on kernels >= 6.2, hwrng_register()
	 * rewrites the requested value (in particular it promotes 0 to the
	 * rng_core.default_quality global, 1024 unless overridden).
	 */
	pr_info("jitterentropy: hwrng device '%s' registered (effective quality %u)\n",
		jent_hwrng.name, jent_hwrng.quality);
#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 2, 0)
	if (!hwrng_quality && jent_hwrng.quality)
		pr_notice("jitterentropy: hwrng_quality=0 was promoted to %u by the hw_random core; the kernel may credit Jitter RNG output to the random pool (boot with rng_core.default_quality=0 to prevent this)\n",
			  jent_hwrng.quality);
#endif

	/*
	 * Non-fatal: the hwrng device is fully functional without the status
	 * export, so a failure here (or a kernel built without CONFIG_PROC_FS,
	 * where jent_proc_dir is NULL) must not abort registration.
	 */
	if (jent_proc_dir) {
		jent_hwrng_proc = proc_create_single(JENT_HWRNG_PROC_NAME, 0444,
						     jent_proc_dir,
						     jent_hwrng_proc_status_show);
		if (!jent_hwrng_proc)
			pr_warn("jitterentropy: failed to create /proc/%s/%s\n",
				JENT_PROC_DIRNAME, JENT_HWRNG_PROC_NAME);
	}

	return 0;
}

void jent_hwrng_exit(void)
{
	/*
	 * Remove the status export first: proc_remove() waits for any in-flight
	 * reader to leave jent_hwrng_proc_status_show() before returning, so the
	 * collector can subsequently be freed without racing a reader.
	 */
	proc_remove(jent_hwrng_proc);
	jent_hwrng_proc = NULL;

	hwrng_unregister(&jent_hwrng);

	if (jent_hwrng_ctx.entropy_collector) {
		jent_entropy_collector_free(jent_hwrng_ctx.entropy_collector);
		jent_hwrng_ctx.entropy_collector = NULL;
	}

	mutex_destroy(&jent_hwrng_ctx.lock);
}
