/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/*
 * Hardware RNG (hwrng) interface for Jitter RNG.
 *
 * This registers the Jitter RNG with the kernel hw_random framework, exposing
 * it as /dev/hwrng (when selected as the current hwrng) and optionally letting
 * the kernel hwrng entropy thread (rngd in-kernel) feed the random pool.
 *
 * A single Jitter RNG instance is allocated when the hwrng is registered (at
 * module load) and freed when it is unregistered (at module unload). read
 * requests are served from that instance and serialized via a mutex.
 *
 * The whole interface can be disabled at compile time by not setting the
 * CONFIG_EXTERNAL_JITTERENTROPY_HWRNG configuration option (see Kbuild.config).
 * In that case the stubs in jitterentropy_hwrng.h are used.
 *
 * Copyright (C) 2026, Stephan Mueller <smueller@chronox.de>
 */

#include <linux/hw_random.h>
#include <linux/kernel.h>
#include <linux/module.h>
#include <linux/mutex.h>
#include <linux/slab.h>

#include "jitterentropy.h"
#include "jitterentropy_hwrng.h"

/*
 * The OSR and flags used to allocate the Jitter RNG instance are shared with
 * the crypto API interface and are configurable via the module parameters of
 * the same name (see jitterentropy_kcapi.c).
 */
extern unsigned int osr;
extern int flags;

/*
 * Entropy quality declared to the hw_random framework, expressed as the number
 * of bits of estimated entropy per 1024 bits of output (maximum 1024).
 *
 * A value of 0 (the default) registers the device without contributing to the
 * kernel random pool automatically; the Jitter RNG output is still available
 * via /dev/hwrng. Set it to a non-zero value (e.g. 1024 as the Jitter RNG is
 * designed to deliver full-entropy, conditioned output) to let the in-kernel
 * hwrng thread feed the entropy pool.
 */
static unsigned int hwrng_quality = 0;
module_param(hwrng_quality, uint, S_IRUSR | S_IRGRP | S_IROTH);
MODULE_PARM_DESC(hwrng_quality,
		 "Jitter RNG hwrng entropy quality (bits per 1024 bits, 0..1024)");

/* State backing the single hwrng instance. */
struct jent_hwrng_ctx {
	struct mutex lock;
	struct rand_data *entropy_collector;
};

static struct jent_hwrng_ctx jent_hwrng_ctx;

static int jent_hwrng_read(struct hwrng *rng, void *data, size_t max, bool wait)
{
	struct jent_hwrng_ctx *ctx = &jent_hwrng_ctx;
	ssize_t ret;

	if (!max)
		return 0;

	mutex_lock(&ctx->lock);
	/*
	 * jent_read_entropy_safe() reallocates the collector on intermittent
	 * health-test failures, hence the indirection. It returns the number
	 * of generated bytes (== max) or a negative error code on a
	 * permanent/generic failure.
	 */
	ret = jent_read_entropy_safe(&ctx->entropy_collector, data, max);
	mutex_unlock(&ctx->lock);

	if (ret < 0)
		return -EFAULT;

	return (int)ret;
}

static struct hwrng jent_hwrng = {
	.name	= "jitterentropy",
	.read	= jent_hwrng_read,
};

int jent_hwrng_init(void)
{
	int ret;

	mutex_init(&jent_hwrng_ctx.lock);

	jent_hwrng_ctx.entropy_collector =
		jent_entropy_collector_alloc(osr, flags);
	if (!jent_hwrng_ctx.entropy_collector) {
		mutex_destroy(&jent_hwrng_ctx.lock);
		return -ENOMEM;
	}

	jent_hwrng.quality = (unsigned short)min_t(unsigned int, hwrng_quality,
						   1024);

	ret = hwrng_register(&jent_hwrng);
	if (ret) {
		pr_err("jitterentropy: failed to register hwrng device: %d\n",
		       ret);
		jent_entropy_collector_free(jent_hwrng_ctx.entropy_collector);
		jent_hwrng_ctx.entropy_collector = NULL;
		mutex_destroy(&jent_hwrng_ctx.lock);
		return ret;
	}

	pr_info("jitterentropy: hwrng device '%s' registered\n",
		jent_hwrng.name);

	return 0;
}

void jent_hwrng_exit(void)
{
	hwrng_unregister(&jent_hwrng);

	if (jent_hwrng_ctx.entropy_collector) {
		jent_entropy_collector_free(jent_hwrng_ctx.entropy_collector);
		jent_hwrng_ctx.entropy_collector = NULL;
	}

	mutex_destroy(&jent_hwrng_ctx.lock);
}
