/* SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause */
/*
 * Kernel crypto API interface for Jitter RNG.
 *
 * Copyright (C) 2023 - 2026, Stephan Mueller <smueller@chronox.de>
 * Copyright (C) 2026, Markus Theil <theil.markus@gmail.com>
 */


#include <linux/init.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/module.h>
#include <linux/ratelimit.h>
#include <linux/slab.h>
#include <linux/string.h>
#include <crypto/internal/rng.h>

#include "jitterentropy.h"
#include "jitterentropy_error.h"
#include "jitterentropy_kcapi.h"
#include "jitterentropy_selftest.h"
#include "jitterentropy_status.h"

/*
 * The OSR and flags used to allocate the per-tfm Jitter RNG instances and the
 * verbose logging switch are configurable via the module parameters of the
 * same name (see jitterentropy_mod.c).
 */
extern unsigned int jent_osr;
extern unsigned int jent_flags;
extern unsigned int jent_verbose;

/***************************************************************************
 * Kernel crypto API interface
 ***************************************************************************/

struct jitterentropy {
	struct mutex jent_lock;
	struct rand_data *entropy_collector;
	/* This instance's own periodic self test. */
	struct jent_selftest_instance selftest;
};

static void jent_kcapi_tfm_cleanup(struct crypto_tfm *tfm)
{
	struct jitterentropy *rng = crypto_tfm_ctx(tfm);

	/*
	 * Before the collector goes away, and outside jent_lock: stopping the
	 * self test waits for a run in progress, which takes jent_lock.
	 */
	jent_selftest_instance_exit(&rng->selftest);

	mutex_lock(&rng->jent_lock);

	if (rng->entropy_collector)
		jent_entropy_collector_free(rng->entropy_collector);
	rng->entropy_collector = NULL;

	mutex_unlock(&rng->jent_lock);
	mutex_destroy(&rng->jent_lock);
}

static int jent_kcapi_log(struct jitterentropy *rng)
{
	static DEFINE_RATELIMIT_STATE(jent_log_rs, DEFAULT_RATELIMIT_INTERVAL,
				      DEFAULT_RATELIMIT_BURST);

	if (!jent_verbose)
		return 0;

	/*
	 * Rate-limit the status as a whole, not per line, so an emitted status
	 * is never cut short. Asked before the document is rendered: a
	 * suppressed status is not worth serializing.
	 */
	if (!__ratelimit(&jent_log_rs))
		return 0;

	/* The collector pointer must not be read without the lock. */
	return jent_status_to_log(&rng->jent_lock, &rng->entropy_collector);
}

static int jent_kcapi_tfm_init(struct crypto_tfm *tfm)
{
	struct jitterentropy *rng = crypto_tfm_ctx(tfm);

	mutex_init(&rng->jent_lock);

	rng->entropy_collector =
		jent_entropy_collector_alloc(jent_osr, jent_flags);
	if (!rng->entropy_collector) {
		mutex_destroy(&rng->jent_lock);
		return -ENOMEM;
	}

	jent_selftest_instance_init(&rng->selftest, &rng->jent_lock,
				    &rng->entropy_collector);

	/*
	 * Best-effort verbose logging: a failure to allocate the status buffer
	 * must not fail the tfm initialization.
	 */
	jent_kcapi_log(rng);

	return 0;
}

static int jent_kcapi_random(struct crypto_rng *tfm,
			     const u8 *src, unsigned int slen,
			     u8 *rdata, unsigned int dlen)
{
	struct jitterentropy *rng = crypto_rng_ctx(tfm);
	struct rand_data *ec;
	bool reallocated;
	ssize_t rc;
	int ret;

	/*
	 * jent_lock also serializes against this instance's own self test:
	 * no data leaves while its run is in progress, and after a failed run
	 * the library refuses with JENT_ERR_SELFTEST, mapped below.
	 */
	mutex_lock(&rng->jent_lock);

	ec = rng->entropy_collector;
	rc = jent_read_entropy_safe(&rng->entropy_collector, rdata, dlen);

	/*
	 * Detect a collector reallocation on health-test recovery while still
	 * holding the lock; rng->entropy_collector must not be read unlocked.
	 */
	reallocated = (ec != rng->entropy_collector);

	if (rc >= 0) {
		/*
		 * Success: jent_read_entropy_safe() returns the number of
		 * generated bytes (== dlen). The crypto API expects 0 on
		 * success, so map any non-negative result accordingly.
		 */
		ret = 0;
	} else {
		/*
		 * Map the error (panicking under FIPS on a permanent
		 * health-test failure). Shared with the hwrng and character
		 * device interfaces, see jitterentropy_error.h.
		 */
		ret = jent_map_read_error(rc);
	}

	mutex_unlock(&rng->jent_lock);

	if (jent_verbose && reallocated) {
		/*
		 * The entropy collector was reallocated
		 *
		 * Do not honor the return code here: In case logging was
		 * unsuccessful, so be it.
		 */
		jent_kcapi_log(rng);
	}

	return ret;
}

static int jent_kcapi_reset(struct crypto_rng *tfm,
			    const u8 *seed, unsigned int slen)
{
	return 0;
}

/*
 * If the code is compiled as part of the kernel, use jitterentropy_rng as name.
 * Otherwise use "jitter_rng" as name as otherwise we have a name clash with
 * the existing old in-kernel variant.
 */
static struct rng_alg jent_alg = {
	.generate		= jent_kcapi_random,
	.seed			= jent_kcapi_reset,
	.seedsize		= 0,
	.base			= {
#ifdef CONFIG_BUILTIN_JITTERENTROPY
		.cra_name               = "jitterentropy_rng",
		.cra_driver_name        = "jitterentropy_rng",
#else
		.cra_name               = "jitter_rng",
		.cra_driver_name        = "jitter_rng",
#endif
		.cra_priority           = 100,
		.cra_ctxsize            = sizeof(struct jitterentropy),
		.cra_module             = THIS_MODULE,
		.cra_init               = jent_kcapi_tfm_init,
		.cra_exit               = jent_kcapi_tfm_cleanup,
	}
};

int __init jent_kcapi_init(void)
{
	return crypto_register_rng(&jent_alg);
}

void jent_kcapi_exit(void)
{
	crypto_unregister_rng(&jent_alg);
}
