#
# Jitter RNG Kernel module configuration options
#
# Usage: Comment out the respective configuration lines below if you do not
#        require the respective option. Please mind the dependencies as
#        mentioned for each option as there is (currently) no automated
#        dependency resolution
#

############################## Basic Configuration #############################

#
# Enable Jitter RNG compilation
# Dependencies: N/A
# The option can either be either 'y' for static linking into the Linux kernel
# (only applicable when compiling as part of the Linux kernel compilation) or
# 'm' for compiling as a kernel module.
#
CONFIG_EXTERNAL_JITTERENTROPY=m

#
# Mark that the Jitter RNG is built as part of the vanilla kernel and thus
# replacing the Jitter RNG copy that is shipped with the Linux kernel.
#
# CONFIG_BUILTIN_JITTERENTROPY=y

#
# Enable test kernel modules to be built
# Dependencies: N/A
# The option can either be either commented out or 'y'.
#
# NOTE: When enabling this options, the Jitter RNG test interface to extract
# raw unconditioned entropy data. Use the getrawentropy tool from the Jitter RNG
# test code.
#
# CONFIG_EXTERNAL_JITTERENTROPY_TESTINTERFACE=y

########################### Jitter RNG Configuration ###########################


