#
# Jitter RNG Kernel module configuration options
#
# Usage: Comment out the respective configuration lines below if you do not
#        require the respective option. Please mind the dependencies as
#        mentioned for each option as there is (currently) no automated
#        dependency resolution
#
#        Every option can also be set on the make command line without editing
#        this file; command line assignments override the values below, e.g.:
#
#           make CONFIG_EXTERNAL_JITTERENTROPY_TESTINTERFACE=y \
#                CONFIG_EXTERNAL_JITTERENTROPY_HWRNG=n
#

############################## Basic Configuration #############################

#
# Enable Jitter RNG compilation
# Dependencies: N/A
# The option can either be either 'y' for static linking into the Linux kernel
# (only applicable when compiling as part of the Linux kernel compilation) or
# 'm' for compiling as a kernel module.
#
CONFIG_EXTERNAL_JITTERENTROPY=m

#
# Mark that the Jitter RNG is built as part of the vanilla kernel and thus
# replacing the Jitter RNG copy that is shipped with the Linux kernel.
#
# CONFIG_BUILTIN_JITTERENTROPY=y

#
# Enable test kernel modules to be built
# Dependencies: N/A
# The option can either be either commented out or 'y'.
#
# NOTE: When enabling this options, the Jitter RNG test interface to extract
# raw unconditioned entropy data. Use the getrawentropy tool from the Jitter RNG
# test code.
#
# CONFIG_EXTERNAL_JITTERENTROPY_TESTINTERFACE=y

#
# Enable the Jitter RNG character device interface
# Dependencies: N/A
# The option can either be either commented out or 'y'.
#
# When enabled, a misc character device /dev/jitterentropy is registered. Each
# open() of the device allocates a dedicated Jitter RNG instance which is freed
# on close(). read() delivers Jitter RNG entropy bytes from that instance.
#
CONFIG_EXTERNAL_JITTERENTROPY_CHARDEV=y

#
# Enable the Jitter RNG hardware RNG (hwrng) interface
# Dependencies: kernel built with CONFIG_HW_RANDOM
# The option can either be either commented out or 'y'.
#
# When enabled, the Jitter RNG is registered with the kernel hw_random
# framework, making it available via /dev/hwrng (when selected as the current
# hwrng) and, depending on the hwrng_quality module parameter, as a source for
# the in-kernel hwrng entropy thread.
#
CONFIG_EXTERNAL_JITTERENTROPY_HWRNG=y

########################### Jitter RNG Configuration ###########################


